# Experiment 1: Reducing size of model by half
model:
  vocab_size: 27
  d_model: 64
  n_heads: 8
  d_ff: 512 # change to 1024?
  n_layers: 4
  max_len: 128
  drop: 0.2

train:
  experiment_name: "base_model"
  epochs: 3 # change to 5 or 10?
  lr: 0.0003
  batch_size: 32
  save_strategy: "steps"
  save_steps: 5000
