# experiement-1a: increasing d_model even further
model:
  vocab_size: 27
  d_model: 512
  n_heads: 4
  d_ff: 512
  n_layers: 2
  max_len: 128
  drop: 0.3

train:
  experiment_name: "experiment-1a"
  epochs: 3
  lr: 0.00001
  batch_size: 32
  save_strategy: "steps"
  save_steps: 5000
