base_config:
  model:
    vocab_size: 27
    d_model: 128
    n_heads: 4
    d_ff: 512
    n_layers: 2
    max_len: 128
    drop: 0.3
  train:
    experiment_name: "base_model"
    epochs: 3
    lr: 0.00001
    batch_size: 32
    save_strategy: "steps"
    save_steps: 5000

grid_search_params:
  d_model: [64, 128, 256, 512]
  n_heads: [1, 2, 4, 8]
  d_ff: [256, 512, 1024]
  lr: [0.00001, 0.00003, 0.00005]
  batch_size: [8, 16, 32]
