base_config:
  model:
    vocab_size: 27
    d_model: 128
    n_heads: 4
    d_ff: 512
    n_layers: 2
    max_len: 128
    drop: 0.3
  
  train:
    experiment_name: "grid_search_TEST"
    epochs: 1
    lr: 0.00001
    batch_size: 32
    save_strategy: "none"
    save_steps: 5000

grid_search_params:
  d_model: [128]
  n_heads: [4]
  d_ff: [512]
  lr: [0.0001, 0.0002]